### ISSUE TITLE
Flag to launch EDITOR, or flags for stdin/stdout

### ISSUE THREAD

**Issue by guppy0130** [guppy0130/markrust#6]
When called without args for input, takes stdin directly, which doesn't make for a great typing experience for anyone (no vim-like controls, for example).

If you launch `$EDITOR` by default:

* Write to the temp directory, then parse that
* Fallback to stdin or vi if unset
* Note that `-i -` should be enough to trigger input via stdin

Otherwise, hide the editor option behind a flag (`-e`?) and note that passing the flag is highly suggested.

**Comment by aeolyus** [comment]
I think keeping input via stdin by default would be better (Unix philosophy) and if you still *really* want this `$EDITOR` feature maybe put it behind a flag like you suggested (`-e`) instead
